weather_mappings={
    'Smoke': 0,
    'Clear': 1,
    'Haze': 2,
    'Scattered Clouds': 3,
    'Shallow Fog': 4,
    'Mostly Cloudy': 5,
    'Fog': 6,
    'Partly Cloudy': 7,
    'Patches of Fog': 8,
    'Thunderstorms and Rain': 9,
    'Overcast': 10,
    'Rain': 11,
    'Light Rain': 12,
    'Drizzle': 13,
    'Mist': 14,
    'Light Drizzle': 15,
    'Thunderstorm': 16,
    'Light Thunderstorms and Rain': 17,
    'Light Thunderstorm': 18,
    'Squalls': 19,
    'Heavy Rain': 20,
    'Light Haze': 21,
    'Widespread Dust': 22,
    'Funnel Cloud': 23,
    'Heavy Thunderstorms and Rain': 24,
    'Heavy Thunderstorms with Hail': 25,
    'Light Rain Showers': 26,
    'Thunderstorms with Hail': 27,
    'Partial Fog': 28,
    'Heavy Fog': 29,
    'Light Fog': 30,
    'Blowing Sand': 31,
    'Sandstorm': 32,
    'Light Hail Showers': 33,
    'Light Sandstorm': 34,
    'Rain Showers': 35
}

reversedict = {
    0: 'Smoke',
    1: 'Clear',
    2: 'Haze',
    3: 'Scattered Clouds',
    4: 'Shallow Fog',
    5: 'Mostly Cloudy',
    6: 'Fog',
    7: 'Partly Cloudy',
    8: 'Patches of Fog',
    9: 'Thunderstorms and Rain',
    10: 'Overcast',
    11: 'Rain',
    12: 'Light Rain',
    13: 'Drizzle',
    14: 'Mist',
    15: 'Light Drizzle',
    16: 'Thunderstorm',
    17: 'Light Thunderstorms and Rain',
    18: 'Light Thunderstorm',
    19: 'Squalls',
    20: 'Heavy Rain',
    21: 'Light Haze',
    22: 'Widespread Dust',
    23: 'Funnel Cloud',
    24: 'Heavy Thunderstorms and Rain',
    25: 'Heavy Thunderstorms with Hail',
    26: 'Light Rain Showers',
    27: 'Thunderstorms with Hail',
    28: 'Partial Fog',
    29: 'Heavy Fog',
    30: 'Light Fog',
    31: 'Blowing Sand',
    32: 'Sandstorm',
    33: 'Light Hail Showers',
    34: 'Light Sandstorm',
    35: 'Rain Showers'
}



direction_mapping={
   'North': 1,
    'West': 4,
    'WNW': 4,
    'East': 3,
    'NW': 1,
    'WSW': 4,
    'ESE': 3,
    'ENE': 3,
    'SE': 3,
    'SW': 2,
    'NNW': 1,
    'NE': 3,
    'SSE': 2,
    'SSW': 2,
    'NNE': 1,
    'South': 2,
    'Variable': 5
}